{{- $fullName := include "logscale-content.fullname" . -}}
{{- $labels := include "logscale-content.labels" . -}}
{{- $managedClusterName := .Values.managedClusterName -}}
{{- $prefix := .Values.repositoryDefault.repoPrefix -}}
{{- $suffix := .Values.repositoryDefault.repoSuffix -}}
{{- $ingestSizeInGB := .Values.repositoryDefault.ingestSizeInGB -}}
{{- $storageSizeInGB := .Values.repositoryDefault.storageSizeInGB -}}
{{- $timeInDays := .Values.repositoryDefault.timeInDays -}}
{{- $allowDataDeletion := .Values.repositoryDefault.allowDataDeletion -}}
{{- range .Values.repositories }}
{{- if .create | default true }}
{{- $crName := print $fullName "-" .name  -}}
apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: {{ $crName }}
  labels:
    {{- $labels | nindent 4 }}  
spec:
  allowDataDeletion: {{ .allowDataDeletion | default $allowDataDeletion }}
  {{- if .description }}
  description: {{ .description }}
  {{- end }}
  managedClusterName: {{ $managedClusterName }}
  name: {{$prefix }}{{ .name }}{{ $suffix }}
  retention:
    ingestSizeInGB: {{ .ingestSizeInGB | default  $ingestSizeInGB }}
    storageSizeInGB: {{ .storageSizeInGB | default $storageSizeInGB }}
    timeInDays: {{ .timeInDays | default $timeInDays }}
---
{{- range .parsers }}
apiVersion: core.humio.com/v1alpha1
kind: HumioParser
metadata:
  name: {{ $crName }}-{{ .name }}
spec:
  managedClusterName: {{ $managedClusterName }}
  repositoryName: {{ $crName }}
  {{ toYaml . | nindent 2 }}  
---
{{- end }}
{{- end }}
{{- end }}
